<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tcc.Themes</AssemblyName>
    <RootNamespace>Tcc.Themes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Tcc.Presentation.Contracts/Tcc.Presentation.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tcc.Architecture.Tests" />
  </ItemGroup>
</Project>
